/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.jamk.paint;

import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.net.URI;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.event.ChangeListener;

/**
 *
 * @author G7902
 */
public class PaintGui extends javax.swing.JPanel
{
    public PaintGui()
    {
        initComponents();
        tabmenu.setFont(new Font( "Arial", Font.PLAIN, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tabmenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        imagebox = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        penbutton_line = new javax.swing.JButton();
        penbutton_circle = new javax.swing.JButton();
        penbutton_rectangle = new javax.swing.JButton();
        penbutton_normal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        functionbutton_save = new javax.swing.JButton();
        functionbutton_clear = new javax.swing.JButton();
        functionbutton_rotateanticlockwise = new javax.swing.JButton();
        functionbutton_open = new javax.swing.JButton();
        functionbutton_rotateclockwise = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        functionbutton_fill = new javax.swing.JButton();
        functionbutton_undo = new javax.swing.JButton();
        functioncheckbox_antialiased = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        toolcheckbox_fillshapes = new javax.swing.JCheckBox();
        toolslider_pensize = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        tooltext_pensize = new javax.swing.JTextField();
        toolpanel_colorbox = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        toolcheckbox_sweepmode = new javax.swing.JCheckBox();
        paintTarget1 = new fi.jamk.paint.PaintTarget();

        setMaximumSize(new java.awt.Dimension(1030, 800));
        setMinimumSize(new java.awt.Dimension(1030, 800));
        setPreferredSize(new java.awt.Dimension(1030, 800));

        tabmenu.setToolTipText("");
        tabmenu.setDoubleBuffered(true);
        tabmenu.setMaximumSize(new java.awt.Dimension(5000, 5000));
        tabmenu.setMinimumSize(new java.awt.Dimension(100, 100));
        tabmenu.setPreferredSize(new java.awt.Dimension(150, 509));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>\n<center>\n<h2><u>Java paint</u></h2>\n<p>Developed by:</p>\n\n<p>Jonah A.</p>\n<p>Eero M.</p>\n<p>Niko R.</p>\n</center>\n</html>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout imageboxLayout = new javax.swing.GroupLayout(imagebox);
        imagebox.setLayout(imageboxLayout);
        imageboxLayout.setHorizontalGroup(
            imageboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imageboxLayout.setVerticalGroup(
            imageboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Paint.png"))); // NOI18N
        jLabel5.setToolTipText("http://www.youtube.com/watch?v=_jmh8omfcZ4");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Link(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("(kirby.wikia.com)");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagebox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(194, 194, 194)
                .addComponent(imagebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabmenu.addTab("Home", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pens", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        penbutton_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/linepen.png"))); // NOI18N
        penbutton_line.setToolTipText("Sets the pen to \"Line\"");

        penbutton_circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circlepen.png"))); // NOI18N
        penbutton_circle.setToolTipText("Sets the pen to \"Circle\"");

        penbutton_rectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rectpen.png"))); // NOI18N
        penbutton_rectangle.setToolTipText("Sets the pen to \"Rectangle\"");

        penbutton_normal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/normalpen.png"))); // NOI18N
        penbutton_normal.setToolTipText("Sets the pen to \"Normal\"");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(penbutton_circle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penbutton_normal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(penbutton_rectangle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penbutton_line, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penbutton_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penbutton_line, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penbutton_circle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penbutton_rectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        tabmenu.addTab("Pens", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Functions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        functionbutton_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        functionbutton_save.setToolTipText("Save the current image");

        functionbutton_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        functionbutton_clear.setToolTipText("Clear the drawing area");

        functionbutton_rotateanticlockwise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ccw.png"))); // NOI18N
        functionbutton_rotateanticlockwise.setToolTipText("Rotates the image counter-clockwise");

        functionbutton_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open.png"))); // NOI18N
        functionbutton_open.setToolTipText("Open a .ypg file");
        functionbutton_open.setPreferredSize(new java.awt.Dimension(127, 23));

        functionbutton_rotateclockwise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cw.png"))); // NOI18N
        functionbutton_rotateclockwise.setToolTipText("Rotates the image clockwise");

        functionbutton_fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fillarea.png"))); // NOI18N
        functionbutton_fill.setToolTipText("Fill the whole drawing area with the color that is currently selected");

        functionbutton_undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/undo.png"))); // NOI18N
        functionbutton_undo.setText("Undo x1");
        functionbutton_undo.setToolTipText("Undo a single last change. Works about 87.7723% of the time.");

        functioncheckbox_antialiased.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        functioncheckbox_antialiased.setSelected(true);
        functioncheckbox_antialiased.setText("Antialiased");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(functioncheckbox_antialiased)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(functionbutton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(functionbutton_open, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(functionbutton_clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(functionbutton_fill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(functionbutton_undo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(functionbutton_rotateanticlockwise, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(functionbutton_rotateclockwise, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(functionbutton_open, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(functionbutton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(functionbutton_rotateanticlockwise, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(functionbutton_rotateclockwise, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(functioncheckbox_antialiased)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(functionbutton_undo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(functionbutton_fill, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(functionbutton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabmenu.addTab("Functions", jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tools", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setPreferredSize(new java.awt.Dimension(224, 285));

        toolcheckbox_fillshapes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolcheckbox_fillshapes.setText("Fill shapes");
        toolcheckbox_fillshapes.setToolTipText("Toggle whet ever the shapes, such as \"Circle\" are filled or not.");

        toolslider_pensize.setSnapToTicks(true);
        toolslider_pensize.setToolTipText("Adjust the pen size");
        toolslider_pensize.setValue(5);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pen size");

        tooltext_pensize.setToolTipText("Adjust the pen size");

        toolpanel_colorbox.setBackground(new java.awt.Color(0, 0, 0));
        toolpanel_colorbox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.lightGray));
        toolpanel_colorbox.setToolTipText("Opens a colorchooser");
        toolpanel_colorbox.setMinimumSize(new java.awt.Dimension(75, 75));
        toolpanel_colorbox.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout toolpanel_colorboxLayout = new javax.swing.GroupLayout(toolpanel_colorbox);
        toolpanel_colorbox.setLayout(toolpanel_colorboxLayout);
        toolpanel_colorboxLayout.setHorizontalGroup(
            toolpanel_colorboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        toolpanel_colorboxLayout.setVerticalGroup(
            toolpanel_colorboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Color");

        toolcheckbox_sweepmode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolcheckbox_sweepmode.setText("Sweep mode");
        toolcheckbox_sweepmode.setToolTipText("Sweepmode makes the program draw what ever it sees on the screen each cycle ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolcheckbox_sweepmode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolcheckbox_fillshapes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(toolslider_pensize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tooltext_pensize, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(toolpanel_colorbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolpanel_colorbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolslider_pensize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tooltext_pensize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toolcheckbox_sweepmode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolcheckbox_fillshapes)
                .addContainerGap())
        );

        javax.swing.GroupLayout paintTarget1Layout = new javax.swing.GroupLayout(paintTarget1);
        paintTarget1.setLayout(paintTarget1Layout);
        paintTarget1Layout.setHorizontalGroup(
            paintTarget1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        paintTarget1Layout.setVerticalGroup(
            paintTarget1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paintTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(paintTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Link(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Link
    {//GEN-HEADEREND:event_Link
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE))
        {
            try 
            {
                desktop.browse(new URI("http://www.youtube.com/embed/TWwqLWxEHFw?iv_load_policy=3&autoplay=1"));
            } 
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Link

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton functionbutton_clear;
    private javax.swing.JButton functionbutton_fill;
    private javax.swing.JButton functionbutton_open;
    private javax.swing.JButton functionbutton_rotateanticlockwise;
    private javax.swing.JButton functionbutton_rotateclockwise;
    private javax.swing.JButton functionbutton_save;
    private javax.swing.JButton functionbutton_undo;
    private javax.swing.JCheckBox functioncheckbox_antialiased;
    private javax.swing.JPanel imagebox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private fi.jamk.paint.PaintTarget paintTarget1;
    private javax.swing.JButton penbutton_circle;
    private javax.swing.JButton penbutton_line;
    private javax.swing.JButton penbutton_normal;
    private javax.swing.JButton penbutton_rectangle;
    private javax.swing.JTabbedPane tabmenu;
    private javax.swing.JCheckBox toolcheckbox_fillshapes;
    private javax.swing.JCheckBox toolcheckbox_sweepmode;
    private javax.swing.JPanel toolpanel_colorbox;
    private javax.swing.JSlider toolslider_pensize;
    private javax.swing.JTextField tooltext_pensize;
    // End of variables declaration//GEN-END:variables

    public JButton getFunctionbutton_clear()
    {
        return functionbutton_clear;
    }

    public JButton getFunctionbutton_save()
    {
        return functionbutton_save;
    }

    public JButton getPenbutton_circle()
    {
        return penbutton_circle;
    }

    public JButton getPenbutton_line()
    {
        return penbutton_line;
    }

    public JButton getPenbutton_normal()
    {
        return penbutton_normal;
    }

    public JButton getPenbutton_rectangle()
    {
        return penbutton_rectangle;
    }

    public JCheckBox getToolcheckbox_fillshapes()
    {
        return toolcheckbox_fillshapes;
    }

    public JSlider getToolslider_pensize()
    {
        return toolslider_pensize;
    }

    public JButton getFunctionbutton_rotateanticlockwise()
    {
        return functionbutton_rotateanticlockwise;
    }
    
    public JButton getFunctionbutton_rotateclockwise()
    {
        return functionbutton_rotateclockwise;
    }
    
    public JTextField getTooltext_pensize()
    {
        return tooltext_pensize;
    }

    public JPanel getToolpanel_colorbox()
    {
        return toolpanel_colorbox;
    }

    public JButton getFunctionbutton_open()
    {
        return functionbutton_open;
    }

    public JCheckBox getToolcheckbox_sweepmode()
    {
        return toolcheckbox_sweepmode;
    }

    public PaintTarget getPaintTarget1()
    {
        return paintTarget1;
    }

    public JButton getFunctionbutton_fill()
    {
        return functionbutton_fill;
    }

    public JButton getFunctionbutton_undo()
    {
        return functionbutton_undo;
    }

    public JTabbedPane getTabmenu()
    {
        return tabmenu;
    }

    public JCheckBox getFunctioncheckbox_antialiased()
    {
        return functioncheckbox_antialiased;
    }

    
    
    public void setActionListeners(ActionListener Al, ChangeListener Cl, MouseListener Ml)
    {
        penbutton_normal.addActionListener(Al);
        penbutton_line.addActionListener(Al);
        penbutton_circle.addActionListener(Al);
        penbutton_rectangle.addActionListener(Al);
        toolpanel_colorbox.addMouseListener(Ml);
        functionbutton_save.addActionListener(Al);
        toolcheckbox_fillshapes.addActionListener(Al);
        functionbutton_clear.addActionListener(Al);
        functionbutton_rotateanticlockwise.addActionListener(Al);
        functionbutton_rotateclockwise.addActionListener(Al);
        functionbutton_open.addActionListener(Al);
        toolcheckbox_sweepmode.addActionListener(Al);
        functionbutton_fill.addActionListener(Al);
        functionbutton_undo.addActionListener(Al);
        functioncheckbox_antialiased.addActionListener(Al);
        toolslider_pensize.addChangeListener(Cl);
        tooltext_pensize.addActionListener(Al);
    }
}
